# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ssbpipelinecontest'
    subscriptionId: '7b2435c6-ad49-485f-86df-8c0f5ee2afd9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ssbazurenew/ssbpipelinedemo/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName Flask Pipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

  displayName: 'Run a multi-line script'
